import eslintConfigPrettier from "eslint-config-prettier/flat";
import nextTs from "eslint-config-next/typescript";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = [
  // playwright-report/ and test-results/ are generated by `pnpm test:e2e`
  // (gitignored, see .prettierignore) — bundled trace-viewer JS in the report
  // otherwise gets linted as if it were project source.
  { ignores: ["supabase/.temp/**", "playwright-report/**", "test-results/**"] },
  ...nextVitals,
  ...nextTs,
  eslintConfigPrettier,
];

export default eslintConfig;
